name: Pipeline
on:
 push:
  branches: ["main"]
 pull_request: 
  branches: ["main"]
jobs:
  build: 
   runs-on: ubuntu-latest
   steps:     
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Code Checkout
        uses: actions/checkout@v2 
      - name: Restore Dependencies
        run: dotnet restore
      - name: Execute Unit Tests
        run: dotnet test ./PassIn.UnitTests
      - name: Execute Integration Tests
        run: dotnet test ./PassIn.IntegrationTests