name: Pipeline
on:
 push:
  branches: ["main"]
jobs:
  build:
   name: Pipeline-PassIn  
   runs-on: ubuntu-latest
   steps:     
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Checkout do código
        uses: actions/checkout@v2 
      - name: Execute Unit Tests
        run: dotnet test ./PassIn.UnitTests
      - name: Execute Integration Tests
        run: dotnet test ./PassIn.IntegrationTests